In [1]:
import pandas as pd
df = pd.read_excel('heartDiseases.xlsx')

In [2]:
df.head()

,id,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,Thal,num,Unnamed: 15,Unnamed: 16
0,1,3,1,1,4,2,1,2.0,4,0.0,2,3,0.0,fixed defect,-1,NaN,NaN
1,2,3,1,4,5,3,0,2.0,2,1.0,1,2,3.0,normal,2,NaN,NaN
2,3,3,1,4,2,2,0,2.0,3,1.0,2,2,2.0,reversable defect,1,NaN,NaN
3,4,0,1,3,3,2,0,0.0,7,0.0,3,3,0.0,normal,-1,NaN,NaN
4,5,1,0,2,3,1,0,2.0,6,0.0,1,1,0.0,normal,-1,NaN,NaN

In [3]:
df = df.drop(df.columns[15], axis=1)
# df = df.drop(df.columns[15], axis=1)

In [4]:
df.head()

,id,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,Thal,num,Unnamed: 16
0,1,3,1,1,4,2,1,2.0,4,0.0,2,3,0.0,fixed defect,-1,NaN
1,2,3,1,4,5,3,0,2.0,2,1.0,1,2,3.0,normal,2,NaN
2,3,3,1,4,2,2,0,2.0,3,1.0,2,2,2.0,reversable defect,1,NaN
3,4,0,1,3,3,2,0,0.0,7,0.0,3,3,0.0,normal,-1,NaN
4,5,1,0,2,3,1,0,2.0,6,0.0,1,1,0.0,normal,-1,NaN

In [5]:
df = df.drop(df.columns[15], axis=1)
# df = df.drop(df.columns[16], axis=1)

In [6]:
df.head()

,id,age,sex,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,Thal,num
0,1,3,1,1,4,2,1,2.0,4,0.0,2,3,0.0,fixed defect,-1
1,2,3,1,4,5,3,0,2.0,2,1.0,1,2,3.0,normal,2
2,3,3,1,4,2,2,0,2.0,3,1.0,2,2,2.0,reversable defect,1
3,4,0,1,3,3,2,0,0.0,7,0.0,3,3,0.0,normal,-1
4,5,1,0,2,3,1,0,2.0,6,0.0,1,1,0.0,normal,-1

In [7]:
columns = ['ca','Thal']
df=df.drop(columns, axis=1)

In [8]:
df.isnull().sum()
df.dropna(axis=0, inplace=True)

In [9]:
# Test model with linear Regressions
df.columns[1]
df.isnull().sum()

id          0
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
num         0
dtype: int64

In [16]:
pip show pandas

Name: pandas
Version: 1.2.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: None
Author-email: None
License: BSD
Location: c:\users\manas\anaconda3\lib\site-packages
Requires: pytz, numpy, python-dateutil
Required-by: statsmodels, seaborn
Note: you may need to restart the kernel to use updated packages.

In [17]:
pip show scikit-learn

Name: scikit-learn
Version: 0.24.1
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: None
Author-email: None
License: new BSD
Location: c:\users\manas\anaconda3\lib\site-packages
Requires: joblib, scipy, numpy, threadpoolctl
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [17]:
#Linear Regression
array=df.values
X = array[:,1:12]
y = array[:,12]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model1_Lr = LinearRegression()
model1_Lr.fit(X_train, y_train)
y_pred = model1_Lr.predict(X_test)

In [18]:
import numpy as np
mse = mean_squared_error(y_test, y_pred)

y_true=np.array(y_test)
for i in range(len(y_true)):
    if y_true[i]>0:
        y_true[i]=1
    else:
        y_true[i]=-1
y_predtest=y_pred
for i in range(len(y_predtest)):
    if y_predtest[i]>0:
        y_predtest[i]=1
    else:
        y_predtest[i]=-1



print()





f1 = f1_score(y_true, y_predtest)
accuracy = accuracy_score(y_true, y_predtest)
cm = confusion_matrix(y_true, y_predtest)
print('mean squared error',mse)
print('f1',f1)
print('accuracy', accuracy)
print('confusion matrix', cm)

mean squared error 1.3581370756319322
f1 0.8623853211009174
accuracy 0.8214285714285714
confusion matrix [[44 25]
 [ 5 94]]

In [24]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression

X = array[:,1:12]
y = array[:,12]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
log_reg = LogisticRegression(solver='lbfgs', max_iter=1000)
log_reg.fit(X_train, y_train)
predicted_classes = log_reg.predict(X_test)

In [29]:

mse = mean_squared_error(y_test, predicted_classes)

y_true=np.array(y_test)
for i in range(len(y_true)):
    if y_true[i]>0:
        y_true[i]=1
    else:
        y_true[i]=-1
y_predtest=predicted_classes
for i in range(len(y_predtest)):
    if y_predtest[i]>0:
        y_predtest[i]=1
    else:
        y_predtest[i]=-1



print()





f1 = f1_score(y_true, y_predtest)
accuracy = accuracy_score(y_true, y_predtest)
cm = confusion_matrix(y_true, y_predtest)
print('mean squared error',mse)
print('f1',f1)
print('accuracy', accuracy)
print('confusion matrix', cm)

# print(y_test.shape) 
# print(predicted_classes.shape)

mean squared error 2.1285714285714286
f1 0.7946428571428571
accuracy 0.780952380952381
confusion matrix [[75 14]
 [32 89]]

In [30]:
from sklearn.preprocessing import PolynomialFeatures

In [40]:
#Polynomial Regression
X = array[:,1:12]
y = array[:,12]
X.reshape(-1,1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

poly_features = PolynomialFeatures(degree=2)
X_poly = poly_features.fit_transform(X_train)

# Fit the polynomial regression model
model = LinearRegression()
model.fit(X_poly, y_train)

X_poly2=poly_features.fit_transform(X_test)

y_pred = model.predict(X_poly2)

In [41]:
mse = mean_squared_error(y_test, y_pred)

y_true=np.array(y_test)
for i in range(len(y_true)):
    if y_true[i]>0:
        y_true[i]=1
    else:
        y_true[i]=-1
y_predtest=y_pred
for i in range(len(y_predtest)):
    if y_predtest[i]>0:
        y_predtest[i]=1
    else:
        y_predtest[i]=-1



print()





f1 = f1_score(y_true, y_predtest)
accuracy = accuracy_score(y_true, y_predtest)
cm = confusion_matrix(y_true, y_predtest)
print('mean squared error',mse)
print('f1',f1)
print('accuracy', accuracy)
print('confusion matrix', cm)

mean squared error 1.4565201161129313
f1 0.8345864661654135
accuracy 0.7904761904761904
confusion matrix [[ 55  34]
 [ 10 111]]

In [43]:
#Softmax Regression
from sklearn.linear_model import LogisticRegression
X = array[:,1:12]
y = array[:,12]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
softmax_reg = LogisticRegression(multi_class='multinomial', solver='lbfgs',max_iter=1000)
softmax_reg.fit(X_train, y_train)

predicted_classes = softmax_reg.predict(X_test)

In [44]:
mse = mean_squared_error(y_test, predicted_classes)

y_true=np.array(y_test)
for i in range(len(y_true)):
    if y_true[i]>0:
        y_true[i]=1
    else:
        y_true[i]=-1
y_predtest=predicted_classes
for i in range(len(y_predtest)):
    if y_predtest[i]>0:
        y_predtest[i]=1
    else:
        y_predtest[i]=-1



print()





f1 = f1_score(y_true, y_predtest)
accuracy = accuracy_score(y_true, y_predtest)
cm = confusion_matrix(y_true, y_predtest)
print('mean squared error',mse)
print('f1',f1)
print('accuracy', accuracy)
print('confusion matrix', cm)

mean squared error 2.1285714285714286
f1 0.7946428571428571
accuracy 0.780952380952381
confusion matrix [[75 14]
 [32 89]]